version: '3'

volumes:
    pgdata: 

networks:
    sunstonet:

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: pg-database
    environment:
      POSTGRES_PASSWORD: "Postgres2021!"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: sunstonedb
    ports:
      - "35432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - sunstonet
      
  adminer:
    image: adminer
    restart: always
    container_name: pg-adminer
    environment:
      PGADMIN_DEFAULT_EMAIL: "sunstone@yahoo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "Postgres2021!"
    ports:
      - "6543:8080"
    depends_on:
      - db
    networks:
      - sunstonet
  
  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - sunstonet
        

